import type { Snapshot } from '@ccstatus/core'

export const sampleSnapshot: Snapshot = {
  version: '2.1.0',
  model: 'Opus 4.8',
  effort: 'high',
  cwd: '/home/you/app',
  repo: true,
  gitRoot: 'app',
  gitBranch: 'main',
  gitWorktree: '',
  added: 1,
  modified: 2,
  deleted: 0,
  ctxTokens: 42000,
  ctxPct: 21,
  cached: 1000,
  input: 2000,
  output: 500,
  total: 3500,
  startedAt: 0,
  cost: null,
  fivePct: 30,
  fiveReset: null,
  weekPct: 10,
  weekReset: null,
  blockReset: null,
  terminalWidth: 0,
  now: 65000,
}
